;;; matugen-theme.el --- Dynamic integration of Matugen colours with Modus Themes -*- lexical-binding: t -*-

;; Copyright (C) 2026 Diego

;; Author: Diego
;; Maintainer: Diego
;; Version: 0.6.0
;; Package-Requires: ((emacs "28.1") (modus-themes "4.0"))
;; Keywords: themes, matugen, wayland, ricing

;;; Commentary:

;; This package provides a seamless and dynamic integration between
;; the Matugen colour generation tool (often used in Wayland environments
;; such as Niri or Hyprland) and the built-in Modus Themes of GNU Emacs.
;;
;; It automatically watches a designated colour palette file generated by
;; Matugen. Upon detecting changes, it recalculates luminance to determine
;; whether the environment dictates a light or dark theme, mathematically
;; scales the colours to preserve the strict AAA accessibility contrast
;; rules of Modus Themes, and dynamically injects the overrides into the
;; active session without requiring a restart.

;;; Code:

(require 'filenotify)
(require 'modus-themes)
(require 'color)

(defgroup matugen-theme nil
  "Dynamic theme switcher based on Matugen colour palettes."
  :group 'modus-themes
  :prefix "matugen-theme-")

(defcustom matugen-theme-colors-file (expand-file-name "~/.config/emacs/matugen-colors.conf")
  "Absolute path to the colour palette file generated by Matugen.
It expects a key-value format typically used for terminal emulators."
  :type 'file
  :group 'matugen-theme)

(defvar matugen-theme--file-watch-descriptor nil
  "Descriptor for the active file system watcher.")

(defun matugen-theme--read-palette ()
  "Parse the Matugen generated file and return an alist of colours."
  (when (file-exists-p matugen-theme-colors-file)
    (let ((colors nil))
      (with-temp-buffer
        (insert-file-contents matugen-theme-colors-file)
        (goto-char (point-min))
        (while (re-search-forward "^\\([a-z-]+\\) = \\(#[0-9a-fA-F]+\\)" nil t)
          (push (cons (intern (match-string 1)) (match-string 2)) colors))
        (goto-char (point-min))
        (while (re-search-forward "^palette = \\([0-9]+\\)=\\(#[0-9a-fA-F]+\\)" nil t)
          (push (cons (intern (format "palette-%s" (match-string 1))) (match-string 2)) colors)))
      colors)))

(defun matugen-theme--mod-color (hex percent lighten)
  "Lighten or darken a HEX colour by PERCENT (0-100).
If LIGHTEN is non-nil, the colour is lightened; otherwise, darkened."
  (if lighten
      (color-lighten-name hex percent)
    (color-darken-name hex percent)))

(defun matugen-theme--is-dark-color (hex)
  "Return non-nil if HEX is a dark colour based on relative luminance."
  (let* ((rgb (color-name-to-rgb hex))
         (r (nth 0 rgb))
         (g (nth 1 rgb))
         (b (nth 2 rgb))
         ;; Standard relative luminance formula for sRGB
         (lum (+ (* 0.299 r) (* 0.587 g) (* 0.114 b))))
    (< lum 0.5)))

;;;###autoload
(defun matugen-theme-reload ()
  "Reload the Matugen palette and apply overrides to Modus Themes."
  (interactive)
  (let ((colors (matugen-theme--read-palette)))
    (when colors
      (let* ((bg (cdr (assq 'background colors)))
             (fg (cdr (assq 'foreground colors)))
             (primary (cdr (assq 'palette-4 colors)))   ;; Blue
             (secondary (cdr (assq 'palette-6 colors))) ;; Cyan
             (tertiary (cdr (assq 'palette-5 colors)))  ;; Magenta
             (error (cdr (assq 'palette-1 colors)))     ;; Red
             (green (cdr (assq 'palette-2 colors)))     ;; Green
             (yellow (cdr (assq 'palette-3 colors)))    ;; Yellow
             
             ;; Automatic Theme Logic:
             ;; Determine if the external palette is dark or light by
             ;; calculating the luminance of the base background colour.
             (is-dark (matugen-theme--is-dark-color bg))
             ;; Force Emacs to adopt the appropriate Modus base theme.
             (base-theme (if is-dark 'modus-vivendi 'modus-operandi))
             
             (bg-dim (matugen-theme--mod-color bg 5 is-dark))
             (bg-alt (matugen-theme--mod-color bg 10 is-dark))
             (bg-active (matugen-theme--mod-color bg 15 is-dark))
             
             ;; Subdued backgrounds for prominent UI elements
             (bg-hl (matugen-theme--mod-color bg 8 is-dark))
             (bg-region (matugen-theme--mod-color bg 20 is-dark))
             (bg-mode-active (matugen-theme--mod-color bg 25 is-dark))
             (bg-mode-inactive (matugen-theme--mod-color bg 12 is-dark))
             (border-mode (matugen-theme--mod-color bg 30 is-dark))
             
             (fg-dim (matugen-theme--mod-color fg 20 (not is-dark))))
        
        ;; Palette adjustments with mathematical scaling to preserve legibility
        (setq modus-themes-common-palette-overrides
              `((bg-main ,bg)
                (fg-main ,fg)
                (bg-dim ,bg-dim)
                (bg-alt ,bg-alt)
                (bg-active ,bg-active)
                (bg-inactive ,bg-dim)
                (border ,bg-alt)
                (fg-dim ,fg-dim)
                
                ;; Highlights and Modeline
                (bg-hl-line ,bg-hl)
                (bg-region ,bg-region)
                (bg-mode-line-active ,bg-mode-active)
                (bg-mode-line-inactive ,bg-mode-inactive)
                (border-mode-line-active ,border-mode)
                (border-mode-line-inactive ,border-mode)
                
                ;; Base semantic colours
                (blue ,primary)
                (cyan ,secondary)
                (magenta ,tertiary)
                (red ,error)
                (green ,green)
                (yellow ,yellow)
                
                ;; Variants tailored for code syntax highlighting
                (blue-cooler ,(matugen-theme--mod-color primary 15 nil))
                (blue-warmer ,(matugen-theme--mod-color primary 15 t))
                (magenta-cooler ,(matugen-theme--mod-color tertiary 15 nil))
                (magenta-warmer ,(matugen-theme--mod-color tertiary 15 t))
                (red-cooler ,(matugen-theme--mod-color error 15 nil))
                (red-warmer ,(matugen-theme--mod-color error 15 t))
                (green-cooler ,(matugen-theme--mod-color green 15 nil))
                (green-warmer ,(matugen-theme--mod-color green 15 t))
                (yellow-cooler ,(matugen-theme--mod-color yellow 15 nil))
                (yellow-warmer ,(matugen-theme--mod-color yellow 15 t))))
        
        ;; Purge all currently active themes to prevent face clashing
        (mapc #'disable-theme custom-enabled-themes)
        (modus-themes-load-theme base-theme)
        
        (when (fboundp 'doom/reload-theme)
          (doom/reload-theme))
        (when (featurep 'solaire-mode)
          (solaire-global-mode -1)
          (solaire-global-mode 1))
          
        (message "Matugen-Theme: Automatically loaded colours from Matugen.")))))

(defun matugen-theme--watcher-callback (event)
  "Callback executed when the designated colour file changes."
  (let ((file (nth 2 event)))
    (when (and (stringp file)
               (string= (file-name-nondirectory file)
                        (file-name-nondirectory matugen-theme-colors-file)))
      (matugen-theme-reload))))

;;;###autoload
(define-minor-mode matugen-theme-mode
  "Global minor mode to synchronise Emacs with Matugen generated palettes."
  :global t
  :lighter " Matugen"
  (if matugen-theme-mode
      (progn
        (when (file-exists-p matugen-theme-colors-file)
          (if after-init-time
              (matugen-theme-reload)
            (add-hook 'emacs-startup-hook #'matugen-theme-reload)))
        
        (unless matugen-theme--file-watch-descriptor
          (let ((dir (file-name-directory matugen-theme-colors-file)))
            (unless (file-exists-p dir)
              (make-directory dir t))
            (setq matugen-theme--file-watch-descriptor
                  (file-notify-add-watch dir
                                         '(change attribute-change)
                                         #'matugen-theme--watcher-callback)))))
    (when matugen-theme--file-watch-descriptor
      (file-notify-rm-watch matugen-theme--file-watch-descriptor)
      (setq matugen-theme--file-watch-descriptor nil))))

(provide 'matugen-theme)
;;; matugen-theme.el ends here
