;;; matugen-theme.el --- Dynamic integration of Matugen colours with Modus Themes -*- lexical-binding: t -*-

;; Copyright (C) 2026 Diego

;; Author: Diego
;; Maintainer: Diego
;; Version: 0.6.0
;; Package-Requires: ((emacs "28.1") (modus-themes "4.0"))
;; Keywords: themes, matugen, wayland, ricing

;;; Commentary:

;; This package provides a seamless and dynamic integration between
;; the Matugen colour generation tool (often used in Wayland environments
;; such as Niri or Hyprland) and the built-in Modus Themes of GNU Emacs.
;;
;; It automatically watches a designated colour palette file generated by
;; Matugen. Upon detecting changes, it recalculates luminance to determine
;; whether the environment dictates a light or dark theme, mathematically
;; scales the colours to preserve the strict AAA accessibility contrast
;; rules of Modus Themes, and dynamically injects the overrides into the
;; active session without requiring a restart.

;;; Code:

(require 'filenotify)
(require 'modus-themes)
(require 'color)

(defgroup matugen-theme nil
  "Dynamic theme switcher based on Matugen colour palettes."
  :group 'modus-themes
  :prefix "matugen-theme-")

(defcustom matugen-theme-colors-file (expand-file-name "~/.config/emacs/matugen-colors.conf")
  "Absolute path to the colour palette file generated by Matugen.
It expects a key-value format typically used for terminal emulators."
  :type 'file
  :group 'matugen-theme)

(defcustom matugen-theme-style 'full
  "Style of the Matugen integration.
- 'full: Override both backgrounds and accents using Matugen colours.
- 'accent: Keep the native Modus Themes backgrounds, but inject Matugen accent colours.
- 'background: Inject Matugen backgrounds, but keep native Modus accent colours for optimal code syntax reading."
  :type '(choice (const :tag "Full (Backgrounds & Accents)" full)
                 (const :tag "Accent only (Native backgrounds)" accent)
                 (const :tag "Background only (Native syntax accents)" background))
  :group 'matugen-theme)

(defun matugen-theme--get-file-path ()
  "Return the Matugen file path. Fallbacks to dankcolors if the primary doesn't exist."
  (if (file-exists-p matugen-theme-colors-file)
      matugen-theme-colors-file
    (let ((fallback (expand-file-name "~/.config/ghostty/themes/dankcolors")))
      (if (file-exists-p fallback) fallback matugen-theme-colors-file))))

(defvar matugen-theme--file-watch-descriptor nil
  "Descriptor for the active file system watcher.")

(defun matugen-theme--read-palette ()
  "Parse the Matugen generated file and return an alist of colours."
  (let ((target-file (matugen-theme--get-file-path)))
    (when (file-exists-p target-file)
      (let ((colors nil))
        (with-temp-buffer
          (insert-file-contents target-file)
          (goto-char (point-min))
          (while (re-search-forward "^\\([a-z-]+\\) = \\(#[0-9a-fA-F]+\\)" nil t)
            (push (cons (intern (match-string 1)) (match-string 2)) colors))
          (goto-char (point-min))
          (while (re-search-forward "^palette = \\([0-9]+\\)=\\(#[0-9a-fA-F]+\\)" nil t)
            (push (cons (intern (format "palette-%s" (match-string 1))) (match-string 2)) colors)))
        colors))))

(defun matugen-theme--hex-to-rgb (hex)
  "Convert a 6-character HEX colour to an RGB list (0.0 - 1.0) independent of the frame."
  (let ((r (/ (string-to-number (substring hex 1 3) 16) 255.0))
        (g (/ (string-to-number (substring hex 3 5) 16) 255.0))
        (b (/ (string-to-number (substring hex 5 7) 16) 255.0)))
    (list r g b)))

(defun matugen-theme--rgb-to-hex (rgb)
  "Convert an RGB list (0.0 - 1.0) back to a 6-character HEX string."
  (format "#%02x%02x%02x"
          (max 0 (min 255 (round (* (nth 0 rgb) 255))))
          (max 0 (min 255 (round (* (nth 1 rgb) 255))))
          (max 0 (min 255 (round (* (nth 2 rgb) 255))))))

(defun matugen-theme--mod-color (hex percent lighten)
  "Lighten or darken a HEX colour by PERCENT (0-100).
If LIGHTEN is non-nil, the colour is lightened; otherwise, darkened.
Uses pure mathematics to avoid Emacs daemon frame approximation bugs."
  (let* ((rgb (matugen-theme--hex-to-rgb hex))
         (hsl (apply #'color-rgb-to-hsl rgb))
         (h (nth 0 hsl))
         (s (nth 1 hsl))
         (l (nth 2 hsl))
         (new-l (if lighten (+ l (/ percent 100.0)) (- l (/ percent 100.0))))
         (clamped-l (max 0.0 (min 1.0 new-l)))
         (new-rgb (color-hsl-to-rgb h s clamped-l)))
    (matugen-theme--rgb-to-hex new-rgb)))

(defun matugen-theme--is-dark-color (hex)
  "Return non-nil if HEX is a dark colour based on relative luminance."
  (let* ((rgb (matugen-theme--hex-to-rgb hex))
         (r (nth 0 rgb))
         (g (nth 1 rgb))
         (b (nth 2 rgb))
         ;; Standard relative luminance formula for sRGB
         (lum (+ (* 0.299 r) (* 0.587 g) (* 0.114 b))))
    (< lum 0.5)))

(defun matugen-theme--luminance (hex)
  "Calculate relative luminance of a HEX colour."
  (let* ((rgb (matugen-theme--hex-to-rgb hex))
         (r (nth 0 rgb))
         (g (nth 1 rgb))
         (b (nth 2 rgb))
         (sR (if (<= r 0.03928) (/ r 12.92) (expt (/ (+ r 0.055) 1.055) 2.4)))
         (sG (if (<= g 0.03928) (/ g 12.92) (expt (/ (+ g 0.055) 1.055) 2.4)))
         (sB (if (<= b 0.03928) (/ b 12.92) (expt (/ (+ b 0.055) 1.055) 2.4))))
    (+ (* 0.2126 sR) (* 0.7152 sG) (* 0.0722 sB))))

(defun matugen-theme--contrast-ratio (hex1 hex2)
  "Calculate WCAG contrast ratio between two HEX colours."
  (let* ((lum1 (matugen-theme--luminance hex1))
         (lum2 (matugen-theme--luminance hex2))
         (l1 (max lum1 lum2))
         (l2 (min lum1 lum2)))
    (/ (+ l1 0.05) (+ l2 0.05))))

(defun matugen-theme--ensure-contrast (hex bg-hex is-dark target-ratio)
  "Adjust HEX until it has at least TARGET-RATIO contrast against BG-HEX."
  (let ((current-hex hex)
        (ratio (matugen-theme--contrast-ratio hex bg-hex))
        (iterations 0)
        (max-iterations 20))
    (while (and (< ratio target-ratio) (< iterations max-iterations))
      (setq current-hex (matugen-theme--mod-color current-hex 5 is-dark))
      (setq ratio (matugen-theme--contrast-ratio current-hex bg-hex))
      (setq iterations (1+ iterations)))
    current-hex))

;;;###autoload
(defun matugen-theme-reload ()
  "Reload the Matugen palette and apply overrides to Modus Themes."
  (interactive)
  (let ((colors (matugen-theme--read-palette)))
    (when colors
      (let* ((bg (cdr (assq 'background colors)))
             ;; Automatic Theme Logic:
             ;; Determine if the external palette is dark or light by
             ;; calculating the luminance of the base background colour.
             (is-dark (matugen-theme--is-dark-color bg))
             
             (fg-main (or (cdr (assoc 'foreground colors)) (if is-dark "#ffffff" "#000000")))
             
             (red-raw (or (cdr (assoc 'red colors)) (cdr (assoc 'palette-1 colors)) bg))
             (red (matugen-theme--ensure-contrast red-raw bg is-dark 4.5))
             (green-raw (or (cdr (assoc 'green colors)) (cdr (assoc 'palette-2 colors)) bg))
             (green (matugen-theme--ensure-contrast green-raw bg is-dark 4.5))
             (yellow-raw (or (cdr (assoc 'yellow colors)) (cdr (assoc 'palette-3 colors)) bg))
             (yellow (matugen-theme--ensure-contrast yellow-raw bg is-dark 4.5))
             (blue-raw (or (cdr (assoc 'blue colors)) (cdr (assoc 'palette-4 colors)) bg))
             (blue (matugen-theme--ensure-contrast blue-raw bg is-dark 4.5))
             (magenta-raw (or (cdr (assoc 'magenta colors)) (cdr (assoc 'palette-5 colors)) bg))
             (magenta (matugen-theme--ensure-contrast magenta-raw bg is-dark 4.5))
             (cyan-raw (or (cdr (assoc 'cyan colors)) (cdr (assoc 'palette-6 colors)) bg))
             (cyan (matugen-theme--ensure-contrast cyan-raw bg is-dark 4.5))
             
             ;; Force Emacs to adopt the appropriate Modus base theme.
             (base-theme (if is-dark 'modus-vivendi 'modus-operandi))
             
             (bg-dim (matugen-theme--mod-color bg 5 is-dark))
             (bg-alt (matugen-theme--mod-color bg 10 is-dark))
             (bg-active (matugen-theme--mod-color bg 15 is-dark))
             
             ;; Subdued backgrounds for prominent UI elements
             (bg-hl (matugen-theme--mod-color bg 8 is-dark))
             (bg-region (matugen-theme--mod-color bg 20 is-dark))
             (bg-mode-active (matugen-theme--mod-color bg 25 is-dark))
             (bg-mode-inactive (matugen-theme--mod-color bg 12 is-dark))
             (border-mode (matugen-theme--mod-color bg 30 is-dark))
             
             (fg-dim (matugen-theme--mod-color fg-main 20 (not is-dark))))
        
        ;; Palette adjustments with mathematical scaling to preserve legibility
        (let* ((accent-overrides
                `((blue ,blue)
                  (cyan ,cyan)
                  (magenta ,magenta)
                  (red ,red)
                  (green ,green)
                  (yellow ,yellow)
                  
                  ;; Variants tailored for code syntax highlighting
                  (blue-cooler ,(matugen-theme--mod-color blue 15 nil))
                  (blue-warmer ,(matugen-theme--mod-color blue 15 t))
                  (magenta-cooler ,(matugen-theme--mod-color magenta 15 nil))
                  (magenta-warmer ,(matugen-theme--mod-color magenta 15 t))
                  (red-cooler ,(matugen-theme--mod-color red 15 nil))
                  (red-warmer ,(matugen-theme--mod-color red 15 t))
                  (green-cooler ,(matugen-theme--mod-color green 15 nil))
                  (green-warmer ,(matugen-theme--mod-color green 15 t))
                  (yellow-cooler ,(matugen-theme--mod-color yellow 15 nil))
                  (yellow-warmer ,(matugen-theme--mod-color yellow 15 t))))
               
               (bg-overrides
                `((bg-main ,bg)
                  (fg-main ,fg-main)
                  (bg-dim ,bg-dim)
                  (bg-alt ,bg-alt)
                  (bg-active ,bg-active)
                  (bg-inactive ,bg-dim)
                  (border ,bg-alt)
                  (fg-dim ,fg-dim)
                  
                  ;; Highlights and Modeline
                  (bg-hl-line ,bg-hl)
                  (bg-region ,bg-region)
                  (bg-mode-line-active ,bg-mode-active)
                  (bg-mode-line-inactive ,bg-mode-inactive)
                  (border-mode-line-active ,border-mode)
                  (border-mode-line-inactive ,border-mode))))
          
          (setq modus-themes-common-palette-overrides
                (cond ((eq matugen-theme-style 'accent) accent-overrides)
                      ((eq matugen-theme-style 'background) bg-overrides)
                      (t (append bg-overrides accent-overrides)))))
        
        ;; Purge all currently active themes to prevent face clashing
        (mapc #'disable-theme custom-enabled-themes)
        (modus-themes-load-theme base-theme)
        
        (when (fboundp 'doom/reload-theme)
          (doom/reload-theme))
        (when (featurep 'solaire-mode)
          (solaire-global-mode -1)
          (solaire-global-mode 1))
        
        ;; Force hl-line-mode to reset and flush its face cache
        (when (bound-and-true-p global-hl-line-mode)
          (global-hl-line-mode -1)
          (global-hl-line-mode 1))
          
        (message "Matugen-Theme: Automatically loaded colours from Matugen.")))))

(defun matugen-theme--watcher-callback (event)
  "Callback executed when the designated colour file changes."
  (let ((file (nth 2 event)))
    (when (and (stringp file)
               (string= (file-name-nondirectory file)
                        (file-name-nondirectory (matugen-theme--get-file-path))))
      (matugen-theme-reload))))

;;;###autoload
(define-minor-mode matugen-theme-mode
  "Global minor mode to synchronise Emacs with Matugen generated palettes."
  :global t
  :lighter " Matugen"
  (if matugen-theme-mode
      (progn
        (when (file-exists-p (matugen-theme--get-file-path))
          (if after-init-time
              (matugen-theme-reload)
            ;; Doom Emacs delays theme loading to its own hook. We must run AFTER it.
            (if (boundp 'doom-init-ui-hook)
                (add-hook 'doom-init-ui-hook #'matugen-theme-reload t)
              (add-hook 'emacs-startup-hook
                        (lambda () (run-with-idle-timer 0.1 nil #'matugen-theme-reload))))))
        
        (unless matugen-theme--file-watch-descriptor
          (let ((dir (file-name-directory (matugen-theme--get-file-path))))
            (unless (file-exists-p dir)
              (make-directory dir t))
            (setq matugen-theme--file-watch-descriptor
                  (file-notify-add-watch dir
                                         '(change attribute-change)
                                         #'matugen-theme--watcher-callback)))))
    (when matugen-theme--file-watch-descriptor
      (file-notify-rm-watch matugen-theme--file-watch-descriptor)
      (setq matugen-theme--file-watch-descriptor nil))))

(provide 'matugen-theme)
;;; matugen-theme.el ends here
